[env:pico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

; Upload settings for automatic reboot and flash
upload_protocol = picotool
upload_port =
monitor_speed = 115200
monitor_port =

; Build flags
build_flags =
    -DARDUINO_RASPBERRY_PI_PICO_W
    -DPICO_W
    -DCYW43_ARCH_THREADSAFE_BACKGROUND=1

; Library dependencies
lib_deps =
